# Generated by Django 2.2.6 on 2022-02-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220131_2056'),
        ('posts', '0003_auto_20220131_1031'),
    ]

    operations = [
    ]
