# Generated by Django 2.2.6 on 2022-02-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_merge_20220212_0535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pub_date',)},
        ),
    ]
