# Generated by Django 2.2.16 on 2022-03-04 22:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_model'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Follow',
        ),
    ]
